### ISSUE TITLE
MicroRunQC + Terra 

### ISSUE THREAD

**Issue by Khrohlow** [CFSAN-Biostatistics/microrunqc-wdl#1]
- [ ] Need to create a MicroRunQC workflow that produces output in a tabular form.
- [ ] Add a column to the MicroRunQC output indicating QC check pass or fail, determined by the number of contigs/n50 values.
- [ ] Submitting the data through the Terra_2_NCBI workflow results in a "pass" in the QC check tab.
- [ ] Once we complete all three steps mentioned above, we will merge them into one workflow. This consolidated workflow takes input sequence files, performs QC checks, and subsequently submits all samples that pass QC to NCBI.

**Comment by Khrohlow** [comment]
"Pass" is determined by the following criteria: SequenceType and Species that meet the contig and coverage threshold, as defined in the QC threshold guidelines established/referenced in Section 5.4 of this link: https://www.protocols.io/view/quality-control-assessment-for-microbial-genomes-g-5jyl8mj16g2w/v5?step=5.4

**Comment by crashfrog** [comment]
Completed in https://github.com/CFSAN-Biostatistics/microrunqc-wdl/commit/3e2b1c785d72d91dec810eabf87be45444c19704 .
